name: webviewx
description: A feature-rich cross-platform webview using webview_flutter for
  mobile and iframe for web. JS interop-ready.
homepage: https://github.com/adrianflutur/webviewx
version: 0.2.3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

  flutter:
    sdk: flutter

  http: ^1.0.0
  path: ^1.8.3
  pointer_interceptor: ^0.9.3+4
  uuid: ^3.0.7
  webview_flutter: ^3.0.4

dev_dependencies:

  flutter_test:
    sdk: flutter

  lint: ^2.1.2
